---
pagetitle: "R for Bioinformatics"
title: "R for Bioinformatics"
subtitle: "Learn to Analyze Genomics, Metagenomics, and Transcriptomics Data with R"
editor: source
---

------------------------------------------------------------------------
ðŸ§‘ Instructor: [Md. Jubayer Hossain](https://hossainlab.github.io/)

ðŸ—“ July 16 - July 31, 2023 \| 9:00 pm - 11:00pm (Bangladesh Time)

ðŸ¨ Medium - Zoom/Google Meet

ðŸ’¥ **Register** with [Google Forms](https://forms.gle/hSH1ACSqDYYVsxie6)

ðŸ’¥ **Registration Fee**: 1020 BDT (for students),1530BDT (for professionals)

ðŸ“ To join private Telegram group for the course, follow instructions in the email you received after registration.
------------------------------------------------------------------------

# Overview
Welcome to the exciting world of bioinformatics! In this course, we will explore the application of the R programming language in the field of bioinformatics. Whether you are a biologist, a computer scientist, or simply someone interested in the intersection of biology and programming, this book is designed to help you get started with using R for bioinformatics.

Bioinformatics combines biology, computer science, statistics, and math to understand complex biological processes. R is a powerful programming language widely used in bioinformatics for data analysis, visualization, and modeling. It has a rich set of packages and libraries for processing biological data.

This course assumes no prior knowledge of R programming, but assumes basic understanding of statistics and bioinformatics. We'll cover data manipulation, visualization, statistics, and common bioinformatics techniques.

Remember, learning a new language and field takes time and practice. Stay persistent, ask questions, and engage actively with the material. Let's embark on this exciting journey into bioinformatics with R. By the end, you'll have the skills to explore and contribute to bioinformatics research.

Enjoy your learning experience, and good luck!


## Learning bbjectives 
- Understand the fundamentals of bioinformatics and its application in biological research.

- Gain a solid foundation in R programming, including data structures, control flow, and functions.

- Learn data manipulation techniques specific to bioinformatics, such as working with DNA sequences and protein structures.

- Gain hands-on experience by working with real-world bioinformatics datasets and applying R to extract valuable information.

- Understand the importance of reproducibility and best practices in bioinformatics research using R.

- Feel confident in applying R for basic bioinformatics tasks and be ready to explore more advanced topics in the field.


## Why R?

-   R is a programming and statistical language.
-   R is used for data Analysis and Visualization.
-   R is simple and easy to learn, read and write.
-   R is an example of a FLOSS (Free Libre and Open Source Software) where one can freely distribute copies of this software, read its source code, modify it, etc.


## Useful resources for learning R

- **DataCamp:** interactive online lessons in R.

    -   Some of the courses are free (particularly community-written lessons like the one you'll do today), but for paid courses, DataCamp costs about 300 SEK / mo.

-   **RStudio Cheat Sheets:** Very helpful 1-2 page overviews of common tasks and packages in R.

-   **Quick-R:** Website with short example-driven overviews of R functionality.

-   **StackOverflow:** Part of the Stack Exchange network, StackOverflow is a Q&A community website for people who work in programming. Tons of incredibly good R users and developers interact on StackExchange, so it's a great place to search for answers to your questions.

-   **R-Bloggers:** Blog aggregagator for posts about R. Great place to learn really cool things you can do in R.

-   **R for Data Science:** Online version of the book by Hadley Wickham, who has written many of the best packages for R, including the Tidyverse, which we will cover.


## Recording of classes

Class lectures will be recorded automatically using cloud. The links will be posted to CHIRAL Classes when they are available.

## Is this course for me?

If your answer to any of the following questions is "yes", then this is the right workshop for you.

-   Do you make summary tables in R (data, survey data, regression models, time-to-event data, adverse event reports)?

-   Do you want your workflow to be reproducible?

-   Are you often frustrated with the immense amount of code required to create great-looking tables in R?

The workshop is designed for those with some experience in R. It will be expected that you can perform basic data manipulation. Experience with the {tidyverse} and the `%>%` operator is a plus, but not required.

## Zoom + Working Virtually

-   Zoom link will be emailed to students

-   Class sessions will be recorded and later posted

-   We will have lectures as well as breakout room sessions to work on labs

-   Please be aware that there is the option to use closed captioning






