---
title: "R for Bioinformatics"
subtitle: "Introduction to Bioconductor"
title-block-banner: true
author:
  - name: Md. Jubayer Hossain
    orcid: 0000-0001-9323-4997
    url: https://hossainlab.github.io/
    affiliations: 
    - CHIRAL Bangladesh
    - Founder & Management Lead 
date: last-modified
date-format: "[Last Updated on] MMMM, YYYY"
format: 
  html:
    toc: true  
    toc-location: right
    toc-title: Table of Contents
    code-link: true
    code-tools: true 
source: editor 
---
## About Bioconductor

-   Bioconductor (BioC) is an open source, community driven software project which provides a framework of tools and databases for the analysis of biological data in R.
-   Started in 2001 with Robert Gentleman.
-   Gained popularity through microarray analysis packages `(MArray/Limma)`.
-   Core reviewed and versioned R packages.
-   Two major releases every year (R has one major release).
-   Great support for High Throughput sequencing.

## Bioconductor Goals

The broad goals of the Bioconductor project are: - To provide widespread access to a broad range of powerful statistical and graphical methods for the analysis of genomic data.

-   To facilitate the inclusion of biological metadata in the analysis of genomic data, e.g. literature data from PubMed, annotation data from Entrez genes.

-   To provide a common software platform that enables the rapid development and deployment of extensible, scalable, and interoperable software.

-   To further scientific understanding by producing high-quality documentation and reproducible research.

-   To train researchers on computational and statistical methods for the analysis of genomic data.

## Installing Bioconductor and packages

Installing Bioconductor/Bioconductor packages is quite straight forward. Every Bioconductor package has a description of the installation R command we can simply copy and paste.

Install Bioconductor:

```{r}
#| label: install-packages 
#| eval: false
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(version = "3.10")

# Install a package:

BiocManager::install("basecallQC")
```
